import { Platform, StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  containerWithHeader: {
    backgroundColor: Platform.OS === 'ios' ? theme.colors.surface : theme.colors.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'android' ? 12 : 32,
  },
  scrollContentWithHeader: {
    paddingTop: 8,
  },
  header: {
    backgroundColor: theme.colors.surface,
    elevation: 0,
    height: Platform.OS === 'ios' ? 44 : undefined,
    borderBottomWidth: Platform.OS === 'ios' ? StyleSheet.hairlineWidth : 0,
    borderBottomColor: theme.colors.outline,
  },
  headerTitle: {
    color: theme.colors.onSurface,
    fontSize: Platform.OS === 'ios' ? 17 : 16,
    fontWeight: '600',
  },
  heroCard: {
    backgroundColor: '#1E63F0',
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
  },
  heroTitle: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 18,
  },
  heroGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  circleWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1,
  },
  circleContainer: {
    width: 108,
    height: 108,
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleBg: {
    position: 'absolute',
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 10,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  circleHalf: {
    position: 'absolute',
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 10,
    borderColor: 'transparent',
    borderLeftColor: '#fff',
    borderTopColor: '#fff',
  },
  circleLeft: {
    position: 'absolute',
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 10,
    borderColor: 'transparent',
    borderRightColor: '#fff',
    borderBottomColor: '#fff',
  },
  circleInner: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#1E63F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleValue: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 20,
  },
  circleLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  screenTitle: {
    color: theme.colors.onSurface,
    fontSize: 22,
    fontWeight: '800',
    // marginBottom: 4,
        marginBottom: 12,
  },
  screenSubtitle: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 90,
  },
  statIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTitle: {
    color: theme.colors.onSurface,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 18,
    flexShrink: 1,
  },
  statSubtitle: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 12,
    marginTop: 2,
  },
  sectionTitle: {
    color: theme.colors.onSurface,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
    marginTop: 4,
  },
  accordionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accordionTitle: {
    color: theme.colors.onSurface,
    fontSize: 16,
    fontWeight: '700',
  },
  accordionMeta: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
  },
  accordionBody: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.outline,
    paddingTop: 10,
    gap: 6,
  },
  accordionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  accordionLabel: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
  },
  accordionValue: {
    color: theme.colors.onSurface,
    fontSize: 14,
    fontWeight: '700',
  },
  actionButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  viewResultsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 6,
    backgroundColor: theme.colors.primary + '1A',
    borderRadius: 12,
  },
  viewResultsText: {
    color: theme.colors.primary,
    fontWeight: '700',
    fontSize: 14,
  },
  outlineButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: theme.colors.primary + '1A',
  },
  outlineButtonText: {
    color: theme.colors.primary,
    fontWeight: '700',
  },
  filledButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
  },
  filledButtonText: {
    color: theme.colors.onPrimary,
    fontWeight: '700',
  },
  caret: {
    transform: [{ rotate: '0deg' }],
  },
});
