import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  heroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    paddingTop: 32,
    position: 'relative',
    borderWidth: theme.dark ? 1 : 0,
    borderColor: theme.colors.outline,
    elevation: theme.dark ? 0 : 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.dark ? 0 : 0.1,
    shadowRadius: 4,
  },
  heroTitlePill: {
    position: 'absolute',
    top: -14,
    alignSelf: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  heroTitleText: {
    color: theme.colors.onPrimary,
    fontWeight: '600',
  },
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  heroLabel: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
    marginBottom: 8,
  },
  heroValue: {
    color: theme.colors.onSurface,
    fontSize: 18,
    fontWeight: '700',
  },
  progressBarBg: {
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.surfaceVariant,
    overflow: 'hidden',
    marginTop: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: theme.colors.primary,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: theme.dark ? 1 : 0,
    borderColor: theme.colors.outline,
    elevation: theme.dark ? 0 : 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.dark ? 0 : 0.1,
    shadowRadius: 4,
  },
  quickActionTitle: {
    color: theme.colors.onSurface,
    fontSize: 16,
    marginTop: 8,
  },
  quickActionSubtitle: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 13,
    marginTop: 4,
  },
  sectionTitle: {
    color: theme.colors.onSurface,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    marginTop: 8,
  },
  accordionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: theme.dark ? 1 : 0,
    borderColor: theme.colors.outline,
    elevation: theme.dark ? 0 : 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.dark ? 0 : 0.1,
    shadowRadius: 4,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accordionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  accordionTitle: {
    color: theme.colors.onSurface,
    fontSize: 16,
    fontWeight: '600',
  },
  statusBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: theme.colors.surfaceVariant,
  },
  statusText: {
    color: theme.colors.onSurface,
    fontSize: 12,
  },
  accordionBody: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.outline,
    paddingTop: 10,
    gap: 6,
  },
  accordionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  accordionLabel: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 13,
  },
  accordionValue: {
    color: theme.colors.onSurface,
    fontSize: 13,
    fontWeight: '600',
  },
  actionButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  outlineButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  outlineButtonText: {
    color: theme.colors.primary,
    fontWeight: '600',
  },
  filledButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
  },
  filledButtonText: {
    color: theme.colors.onPrimary,
    fontWeight: '600',
  },
  viewResultsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginTop: 4,
    gap: 6,
  },
  viewResultsText: {
    color: theme.colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  // Helper for success/error colors which might not be in theme
  textSuccess: {
    color: '#34A853',
  },
  textError: {
    color: theme.colors.error,
  },
});
