export const ROUTES = {
  SPLASH: 'Splash',
  AUTH: 'Auth',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  ACCOUNT: 'Account',
  PROFILE_INFO: 'ProfileInfo',
  HELP: 'Help',
  SUPPORT_REQUEST: 'SupportRequest',
  PRIVACY: 'Privacy',
  HELP_TOPIC: 'HelpTopic',
  EXAM: 'Exam',
  EXAM_RESULTS: 'ExamResults',
  BOOK: 'Book',
  CHAPTER: 'Chapter',
  READER: 'Reader',
  READER_STACK: 'ReaderStack',
  TEST: 'Test',
  SETTINGS: 'Settings',
  REVIEW_QUESTIONS: 'ReviewQuestions',
  BILLING: 'Billing',
  MOCK_EXAMS: 'MockExams',
  CHAPTER_EXAMS: 'ChapterExams',
} as const;
