export const ROUTES = {
  AUTH: 'Auth',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  ACCOUNT: 'Account',
  PROFILE_INFO: 'ProfileInfo',
  HELP: 'Help',
  PRIVACY: 'Privacy',
  EXAM: 'Exam',
  EXAM_RESULTS: 'ExamResults',
  BOOK: 'Book',
  CHAPTER: 'Chapter',
  READER: 'Reader',
  READER_STACK: 'ReaderStack',
  TEST: 'Test',
  SETTINGS: 'Settings',
  REVIEW_QUESTIONS: 'ReviewQuestions',
};
