import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    iconButton: {
      padding: 8,
      borderRadius: 12,
      backgroundColor: theme.dark ? theme.colors.surfaceVariant : '#E8EAED',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.colors.onBackground,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
      gap: 16,
    },
    hero: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderWidth: theme.dark ? 1 : 0,
      borderColor: theme.colors.outline,
      shadowColor: '#000',
      shadowOpacity: theme.dark ? 0.2 : 0.05,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      elevation: 4,
    //   alignItems: 'flex-start',
    //   gap: 10,
    },
    heroIcon: {
      width: 46,
      height: 46,
      borderRadius: 12,
      backgroundColor: theme.dark ? 'rgba(29,155,240,0.16)' : '#E8F1FF',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 4,
    },
    heroTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.onSurface,
    },
    heroSubtitle: {
      fontSize: 14,
      color: theme.colors.onSurface,
      opacity: 0.75,
    },
    bodyCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: theme.dark ? 1 : 0,
      borderColor: theme.colors.outline,
      shadowColor: '#000',
      shadowOpacity: theme.dark ? 0.2 : 0.05,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      elevation: 4,
      gap: 10,
    },
    bodyText: {
      fontSize: 15,
      lineHeight: 22,
      color: theme.colors.onSurface,
    },
    section: {
      gap: 8,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.onSurface,
    },
    paragraph: {
      fontSize: 15,
      lineHeight: 22,
      color: theme.colors.onSurface,
      opacity: 0.9,
    },
    bulletRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
    },
    bulletIcon: {
      marginTop: 2,
    },
    statGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: theme.dark ? 1 : 0,
      borderColor: theme.colors.outline,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOpacity: theme.dark ? 0.2 : 0.05,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 3,
    },
    statLabel: {
      fontSize: 13,
      color: theme.colors.onSurface,
      opacity: 0.75,
      marginBottom: 4,
      textAlign: 'center',
    },
    statValue: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.primary,
      textAlign: 'center',
    },
    statValueSmall: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.primary,
    },
    helpfulRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
    },
    pillButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.outline,
      backgroundColor: theme.dark ? theme.colors.surfaceVariant : theme.colors.surface,
    },
    pillLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.onSurface,
    },
    emailButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: theme.colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      shadowColor: '#000',
      shadowOpacity: theme.dark ? 0.25 : 0.15,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 10,
      elevation: 5,
    },
    emailButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '700',
    },
  });
